
export const GET_RESTAURNTS_ORDER_REQUEST= 'GET_RESTAURNTS_ORDER_REQUEST';
export const GET_RESTAURNTS_ORDER_SUCCESS= 'GET_RESTAURNTS_ORDER_SUCCESS';
export const GET_RESTAURNTS_ORDER_FAILURE= 'GET_RESTAURNTS_ORDER_FAILURE';

export const UPDATE_ORDER_STATUS_REQUEST= 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS= 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE= 'UPDATE_ORDER_STATUS_FAILURE';

export const FILTER_ORDER_REQUEST= 'FILTER_ORDER_REQUEST';
export const FILTER_ORDER_SUCCESS= 'FILTER_ORDER_SUCCESS';
export const FILTER_ORDER_FAILURE= 'FILTER_ORDER_FAILURE';