// Order Assignment Actions
export const ASSIGN_ORDER_TO_DELIVERY_PERSON_REQUEST = 'ASSIGN_ORDER_TO_DELIVERY_PERSON_REQUEST';
export const ASSIGN_ORDER_TO_DELIVERY_PERSON_SUCCESS = 'ASSIGN_ORDER_TO_DELIVERY_PERSON_SUCCESS';
export const ASSIGN_ORDER_TO_DELIVERY_PERSON_FAILURE = 'ASSIGN_ORDER_TO_DELIVERY_PERSON_FAILURE';

// Order Status Actions
export const GET_ORDERS_BY_STATUS_REQUEST = 'GET_ORDERS_BY_STATUS_REQUEST';
export const GET_ORDERS_BY_STATUS_SUCCESS = 'GET_ORDERS_BY_STATUS_SUCCESS';
export const GET_ORDERS_BY_STATUS_FAILURE = 'GET_ORDERS_BY_STATUS_FAILURE';

// Order By your id
export const GET_ORDERS_BY_ID_REQUEST = 'GET_ORDERS_BY_ID_REQUEST';
export const GET_ORDERS_BY_ID_SUCCESS = 'GET_ORDERS_BY_ID_SUCCESS';
export const GET_ORDERS_BY_ID_FAILURE = 'GET_ORDERS_BY_ID_FAILURE';


// Delivery History Actions
export const GET_DELIVERY_HISTORY_REQUEST = 'GET_DELIVERY_HISTORY_REQUEST';
export const GET_DELIVERY_HISTORY_SUCCESS = 'GET_DELIVERY_HISTORY_SUCCESS';
export const GET_DELIVERY_HISTORY_FAILURE = 'GET_DELIVERY_HISTORY_FAILURE';