export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const GET_USERS_ORDERS_REQUEST = "GET_USERS_ORDERS_REQUEST";
export const GET_USERS_ORDERS_SUCCESS = "GET_USERS_ORDERS_SUCCESS";
export const GET_USERS_ORDERS_FAILURE = "GET_USERS_ORDERS_FAILURE";

export const GET_USERS_DELIVERYADDRESS_REQUEST = "GET_USERS_DELIVERYADDRESS_REQUEST";
export const GET_USERS_DELIVERYADDRESS_SUCCESS = "GET_USERS_DELIVERYADDRESS_SUCCESS";
export const GET_USERS_DELIVERYADDRESS_FAILURE = "GET_USERS_DELIVERYADDRESS_FAILURE";

export const Delete_Address_Order_REQUEST = "Delete_Address_Order_REQUEST";
export const Delete_Address_Order_SUCCESS = "Delete_Address_Order_SUCCESS";
export const Delete_Address_Order_FAILURE = "Delete_Address_Order_FAILURE";

