export const GET_ALL_USERS_REQUEST="GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS="GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE="GET_ALL_USERS_FAILURE";

export const GET_ALL_RESTAURANTS_REQUEST="GET_ALL_RESTAURANTS_REQUEST";
export const GET_ALL_RESTAURANTS_SUCCESS="GET_ALL_RESTAURANTS_SUCCESS";
export const GET_ALL_RESTAURANTS_FAILURE="GET_ALL_RESTAURANTS_FAILURE";

export const GET_ALL_ORDERS_REQUEST="GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS="GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAILURE="GET_ALL_ORDERS_FAILURE";

